version: '3'

services:
  client:
    build: 
      context: ./client
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - CHATBOT_API_URL=http://chatbot:5000
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - chatbot
    networks:
      - app-network
    command: npm run start

  chatbot:
    build: 
      context: ./chatbot-deployment
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    volumes:
      - ./chatbot-deployment:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 