const tintColor = "#18253f";

export default {
  tintColor,
  primaryGreen: "#1f1f1f",
  grayColor: "#66727e",
  lightGray: "#DCDCDC",
  chosenFilterBackgroundColor: "#deebff",
  chosenFilterColor: "#18253f",
  backgroundColor: "#86909a",
  bannerColor: "#18253f",
  filledColor: "#18253f",
  initialColor: "#DCDCDC",
  _filledColor: "#77ba99",
  cardColor: "#f1f7ff",
  tabIconDefault: "#ccc",
  headerTintColor: "#fff",
  activeTintColor: tintColor,
  inactiveTintColor: "#000",
  tabIconSelected: tintColor,
  tabBar: "#fefefe",
  errorBackground: "red",
  errorText: "#fff",
  warningBackground: "#EAEB5E",
  warningText: "#666804",
  noticeBackground: tintColor,
  noticeText: "#fff",
  normalScreenHeaderSize: 21,
  smallScreenHeaderSize: 16,
  normalScreenDescriptionSize: 16,
  smallScreenDescriptionSize: 10,
  titleText: {
    fontSize: 15,
  },
  paragraphText: {
    fontSize: 12,
  },
};
