export const TEST_TYPE = "TEST_TYPE";
//auth
export const AUTH_TYPES = {
  SIGN_IN: "SIGN_IN",
  AUTH_ERROR : "AUTH_ERROR",
  SIGN_OUT : "SIGN_OUT",
  REFRESH_TOKEN : "REFRESH_TOKEN",
  LOAD_ME : "LOAD_ME",
  SIGN_IN_INIT: "SIGN_IN_INIT",
  SIGN_IN_FINISH: "SIGN_IN_FINISH",
};

//profile
export const UPDATE_ADMIN_TYPES = {
  UPDATE_ADMIN: "UPDATE_ADMIN",
  UPDATE_ADMIN_INIT: "UPDATE_ADMIN_INIT",
  UPDATE_ADMIN_FINISH: "UPDATE_ADMIN_FINISH",
};
export const UPDATE_USER = "UPDATE_USER";
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_BANK = "UPDATE_BANK";
export const GET_BANK_INFO = "GET_BANK_INFO";

// alert
export const GLOBAL_ERROR = "GLOBAL_ERROR";
export const SUCCESS = "SUCCESS";

//socket
export const SAVE_SOCKET_USER = "SAVE_SOCKET_USER";

//notification
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const READ_NOTIFICATION = "READ_NOTIFICATION";

//order
export const ORDERS_TYPES = {
  GET_ORDERS : "GET_ORDERS",
  GET_ORDERS_INIT: "GET_ORDERS_INIT",
  GET_ORDERS_FINISH: "GET_ORDERS_FINISH",
};
export const ORDER_TYPES = {
  GET_ORDER : "GET_ORDER",
  GET_ORDER_INIT: "GET_ORDER_INIT",
  GET_ORDER_FINISH: "GET_ORDER_FINISH",
  CANCEL_ORDER : "CANCEL_ORDER"
};
export const TOGGLE_ORDER_APPROVAL_TYPES = {
  TOGGLE_ORDER_APPROVAL_INIT: "TOGGLE_ORDER_APPROVAL_INIT",
  TOGGLE_ORDER_APPROVAL_FINISH: "TOGGLE_ORDER_APPROVAL_FINISH",
  TOGGLE_ORDER_APPROVAL : "TOGGLE_ORDER_APPROVAL",
};
export const TOGGLE_TOBERETURN_ORDER_TYPES = {
  TOGGLE_TOBERETURN_ORDER_INIT: "TOGGLE_TOBERETURN_ORDER_INIT",
  TOGGLE_TOBERETURN_ORDER_FINISH: "TOGGLE_TOBERETURN_ORDER_FINISH",
  TOGGLE_TOBERETURN_ORDER : "TOGGLE_TOBERETURN_ORDER",
};
export const CANCEL_ORDER_TYPES = {
  CANCEL_ORDER_INIT: "CANCEL_ORDER_INIT",
  CANCEL_ORDER_FINISH: "CANCEL_ORDER_FINISH",
  CANCEL_ORDER : "CANCEL_ORDER",
};

//product
export const PRODUCTS_TYPES = {
  GET_PRODUCTS : "GET_PRODUCTS",
  GET_PRODUCTS_INIT: "GET_PRODUCTS_INIT",
  GET_PRODUCTS_FINISH: "GET_PRODUCTS_FINISH",
};
export const PRODUCT_TYPES = {
  GET_PRODUCT : "GET_PRODUCT",
  GET_PRODUCT_INIT: "GET_PRODUCT_INIT",
  GET_PRODUCT_FINISH: "GET_PRODUCT_FINISH",
  DELETE_PRODUCT : "DELETE_PRODUCT"
};

export const ADD_PRODUCT_TYPES = {
  ADD_PRODUCT : "ADD_PRODUCT",
  ADD_PRODUCT_INIT: "ADD_PRODUCT_INIT",
  ADD_PRODUCT_FINISH: "ADD_PRODUCT_FINISH",
};
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_BRANDS = "GET_BRANDS";
export const UPLOAD_IMAGES = "UPLOAD_IMAGES";
export const REMOVE_IMAGE = "REMOVE_IMAGE"//add product ma use hunchha
export const REMOVE_UPLOAD_IMAGES = "REMOVE_UPLOAD_IMAGES";//edit prodcut unmount huda use hunchha

//superadmin
export const ADMINS_TYPES = {
  GET_ADMINS: "GET_ADMINS",
  GET_ADMINS_INIT: "GET_ADMINS_INIT",
  GET_ADMINS_FINISH: "GET_ADMINS_FINISH",
};
export const ADMIN_TYPES = {
  GET_ADMIN: "GET_ADMIN",
  GET_ADMIN_INIT: "GET_ADMIN_INIT",
  GET_ADMIN_FINISH: "GET_ADMIN_FINISH",
};

export const ADMIN_APPROVAL_TYPES = {
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  BLOCK_UNBLOCK_USER_REQUEST: 'BLOCK_UNBLOCK_USER_REQUEST',
  BLOCK_UNBLOCK_USER_SUCCESS: 'BLOCK_UNBLOCK_USER_SUCCESS',
  BLOCK_UNBLOCK_USER_FAILURE: 'BLOCK_UNBLOCK_USER_FAILURE',
  FLIP_ADMIN_BUSINESS_APPROVAL_REQUEST: 'FLIP_ADMIN_BUSINESS_APPROVAL_REQUEST',
  FLIP_ADMIN_BUSINESS_APPROVAL_SUCCESS: 'FLIP_ADMIN_BUSINESS_APPROVAL_SUCCESS',
  FLIP_ADMIN_BUSINESS_APPROVAL_FAILURE: 'FLIP_ADMIN_BUSINESS_APPROVAL_FAILURE',
  FLIP_ADMIN_BANK_APPROVAL_REQUEST: 'FLIP_ADMIN_BANK_APPROVAL_REQUEST',
  FLIP_ADMIN_BANK_APPROVAL_SUCCESS: 'FLIP_ADMIN_BANK_APPROVAL_SUCCESS',
  FLIP_ADMIN_BANK_APPROVAL_FAILURE: 'FLIP_ADMIN_BANK_APPROVAL_FAILURE',
  FLIP_ADMIN_WAREHOUSE_APPROVAL_REQUEST: 'FLIP_ADMIN_WAREHOUSE_APPROVAL_REQUEST',
  FLIP_ADMIN_WAREHOUSE_APPROVAL_SUCCESS: 'FLIP_ADMIN_WAREHOUSE_APPROVAL_SUCCESS',
  FLIP_ADMIN_WAREHOUSE_APPROVAL_FAILURE: 'FLIP_ADMIN_WAREHOUSE_APPROVAL_FAILURE',
  FLIP_ADMIN_ACCOUNT_APPROVAL_REQUEST: 'FLIP_ADMIN_ACCOUNT_APPROVAL_REQUEST',
  FLIP_ADMIN_ACCOUNT_APPROVAL_SUCCESS: 'FLIP_ADMIN_ACCOUNT_APPROVAL_SUCCESS',
  FLIP_ADMIN_ACCOUNT_APPROVAL_FAILURE: 'FLIP_ADMIN_ACCOUNT_APPROVAL_FAILURE',
  BLOCK_UNBLOCK_ADMIN_REQUEST: 'BLOCK_UNBLOCK_ADMIN_REQUEST',
  BLOCK_UNBLOCK_ADMIN_SUCCESS: 'BLOCK_UNBLOCK_ADMIN_SUCCESS',
  BLOCK_UNBLOCK_ADMIN_FAILURE: 'BLOCK_UNBLOCK_ADMIN_FAILURE',
  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
};

export const BEING_ADMIN = "BEING_ADMIN"
export const BEING_SUPERADMIN = "BEING_SUPERADMIN"
export const TOGGLE_PRODUCT_STATUS_TYPES = {
  TOGGLE_PRODUCT_STATUS: "TOGGLE_PRODUCT_STATUS",
  TOGGLE_PRODUCT_STATUS_INIT: "TOGGLE_PRODUCT_STATUS_INIT",
  TOGGLE_PRODUCT_STATUS_FINISH: "TOGGLE_PRODUCT_STATUS_FINISH",
};

// business
export const BUSINESS_TYPES = {
  GET_BUSINESS_INFO: "GET_BUSINESS_INFO",
  BUSINESS_ERROR: "BUSINESS_ERROR"
};

export const BANK_TYPES = {
  GET_BANK_INFO: 'GET_BANK_INFO',
  UPDATE_BANK_INFO: 'UPDATE_BANK_INFO',
  BANK_ERROR: 'BANK_ERROR'
};

export const WAREHOUSE_TYPES = {
  GET_WAREHOUSE_INFO: 'GET_WAREHOUSE_INFO',
  UPDATE_WAREHOUSE_INFO: 'UPDATE_WAREHOUSE_INFO',
  WAREHOUSE_ERROR: 'WAREHOUSE_ERROR'
};

// Sale
export const SALE_TYPES = {
  GET_ALL_SALES: "GET_ALL_SALES",
  GET_ALL_SALES_INIT: "GET_ALL_SALES_INIT",
  GET_ALL_SALES_FINISH: "GET_ALL_SALES_FINISH",

  GET_SALES_BY_ADMIN: "GET_SALES_BY_ADMIN",
  GET_SALES_BY_ADMIN_INIT: "GET_SALES_BY_ADMIN_INIT",
  GET_SALES_BY_ADMIN_FINISH: "GET_SALES_BY_ADMIN_FINISH",

  GET_ACTIVE_SALES: "GET_ACTIVE_SALES",
  GET_ACTIVE_SALES_INIT: "GET_ACTIVE_SALES_INIT",
  GET_ACTIVE_SALES_FINISH: "GET_ACTIVE_SALES_FINISH",

  CREATE_SALE: "CREATE_SALE",
  CREATE_SALE_INIT: "CREATE_SALE_INIT",
  CREATE_SALE_FINISH: "CREATE_SALE_FINISH",
};

export const CATEGORY_TYPES = {
  GET_BRANDS_REQUEST: 'GET_BRANDS_REQUEST',
  GET_BRANDS_SUCCESS: 'GET_BRANDS_SUCCESS',
  GET_BRANDS_FAILURE: 'GET_BRANDS_FAILURE',

  CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',

  FLIP_CATEGORY_REQUEST: 'FLIP_CATEGORY_REQUEST',
  FLIP_CATEGORY_SUCCESS: 'FLIP_CATEGORY_SUCCESS', 
  FLIP_CATEGORY_FAILURE: 'FLIP_CATEGORY_FAILURE',

  DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE'
};
