// Category Types
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const GET_PRODUCT_BRANDS = 'GET_PRODUCT_BRANDS'; 

export const CATEGORY_TYPES = {
    GET_BRANDS_REQUEST: 'GET_BRANDS_REQUEST',
    GET_BRANDS_SUCCESS: 'GET_BRANDS_SUCCESS',
    GET_BRANDS_FAILURE: 'GET_BRANDS_FAILURE',
  
    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',

    FLIP_CATEGORY_REQUEST: 'FLIP_CATEGORY_REQUEST',
    FLIP_CATEGORY_SUCCESS: 'FLIP_CATEGORY_SUCCESS', 
    FLIP_CATEGORY_FAILURE: 'FLIP_CATEGORY_FAILURE',
  
    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE'
  };